export const LOGIN_SCREEN = 'LOGIN_SCREEN';

// TAB
export const ALERT_SCREEN = 'ALERT_SCREEN';
export const JOBS_SCREEN = 'JOBS_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';

//
export const JOB_DETAILS_SCREEN = 'JOB_DETAILS_SCREEN';
