export const LOGIN_SCREEN = 'LOGIN_SCREEN';

// TAB
export const ALERT_SCREEN = 'ALERT_SCREEN';
export const JOBS_SCREEN = 'JOBS_SCREEN';
export const DRAWER_SCREEN = 'DRAWER_SCREEN';

//
export const JOB_DETAILS_SCREEN = 'JOB_DETAILS_SCREEN';
export const SIGNATURE_SCREEN = 'SIGNATURE_SCREEN';
export const FAIL_JOB_SCREEN = 'FAIL_JOB_SCREEN';
export const CUSTOM_MODAL_SCREEN = 'CUSTOM_MODAL_SCREEN';
export const UPLOAD_HISTORY_SCREEN = 'UPLOAD_HISTORY_SCREEN';
export const ADDRESS_SCREEN = 'ADDRESS_SCREEN';
export const DRIVER_MESSAGE_SCREEN = 'DRIVER_MESSAGE_SCREEN';
export const SCAN_CODE_SCREEN = 'SCAN_CODE_SCREEN';
export const ADD_SERVICES_SCREEN = 'ADD_SERVICES_SCREEN';
export const BLUETOOTH_PRINTER_SCREEN = 'BLUETOOTH_PRINTER_SCREEN';
export const PREVIEW_SCREEN = 'PREVIEW_SCREEN';
export const ADD_WASTE_TYPES_SCREEN = 'ADD_WASTE_TYPES_SCREEN';
export const BIN_INPUT_SCREEN = 'BIN_INPUT_SCREEN';
