export const LOGIN_SCREEN = 'LOGIN_SCREEN';

// TAB
export const ALERT_SCREEN = 'ALERT_SCREEN';
export const JOBS_SCREEN = 'JOBS_SCREEN';
export const DRAWER_SCREEN = 'DRAWER_SCREEN';

//
export const JOB_DETAILS_SCREEN = 'JOB_DETAILS_SCREEN';
export const SIGNATURE_SCREEN = 'SIGNATURE_SCREEN';
export const FAIL_JOB_SCREEN = 'FAIL_JOB_SCREEN';
export const CUSTOM_MODAL_SCREEN = 'CUSTOM_MODAL_SCREEN';
export const UPLOAD_HISTORY_SCREEN = 'UPLOAD_HISTORY_SCREEN';
export const ADDRESS_SCREEN = 'ADDRESS_SCREEN';
export const DRIVER_NOTE_SCREEN = 'DRIVER_NOTE_SCREEN';
export const BIN_INFO_SCREEN = 'BIN_INFO_SCREEN';
export const SCAN_CODE_SCREEN = 'SCAN_CODE_SCREEN';
export const ADD_SERVICES_SCREEN = 'ADD_SERVICES_SCREEN';
